language: node_js
sudo: required
dist: trusty
node_js:
  - "5"

before_script:
  - npm install -g typings typescript istanbul gulp-cli mocha
  - export CHROME_BIN=/usr/bin/google-chrome
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - typings install

script:
  - npm run-script coverage-server
  - npm run-script coveralls-server
  - npm run-script test-server
  - npm run-script test-client

services: mongodb
addons:
  apt:
    sources:
    - google-chrome
    packages:
    - google-chrome-stable
