language: node_js

node_js:
  - "5"

before_script:
  - npm install -g typings typescript istanbul gulp-cli mocha
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - typings install

script:
  - npm run-script coverage-server
  - npm run-script coveralls-server
  - npm run-script test-server
  - npm run-script test-client

services: mongodb
