language: node_js
node_js:
- 4.4.6
env:
- CXX=g++-4.8
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - g++-4.8
matrix:
  fast_finish: true
  allow_failures:
  - node_js: 5.12.0
before_script:
- npm install -g gulp-cli
- gem install sass
services: mongodb
deploy:
  provider: heroku
  app: bottest-guillermo
  run:
  - cd dist/ && npm start
  strategy: git
  api_key:
    secure: dZWeUkVDM/W+v96Kl6pl1vXduOiX9r+ccDErZ1uKZXR/IOTJ1eFkzpAqZr4cjNnGF5Klx9NOg46f+vXB+vvD31vA3N9u96k60QQ0YBJewe8jDy9fYZ8SF3pRocCs5EVatq6swmEvWy7T2ofFjFaAfPAx8cp+Yt/oYs8b11yIkTiN9/n30gVmd1jQR4YebnpxALbJmc5m2RBOHSGX2NkGKptSxu0vMqIUuvxfI1v36OBooLQnmFpH6EFfzjwbkqVUgS/PsxZt8PmxcVAT4LZn/9LPUY1DsS9d5xDxtNcwn7loLS7Risu/nGz66zfHhfT75YySOaS9pRYpr2ZD7p8jbKNSTM7JU1cfYy0ddNoDSIMfvH6cHTDAq/1A5BA195ANG7p29VRdnc0VugDq8qSqII/Z8fRh9ekEIqWLsR+faMC0yXnX74sNiPcih4g0LSpAJl4NjHvmOhwLfTFR+VdH1m6E/61k5Q9p5pjNqksFiltnfdG4zqfUGX9fErtgsYnUTX8MJKWGedmur7gca6N7Aqv6xFFibZi4TSc6/8fnuP4yCB83TfULlP6eo5ZbMiidkPxmqywKdQIfMCvGVqbknElzgdhJWRdVYndnm+KPSn+2gYfDEmMknYSAPmkyw3OXrk+dfLZxxvUU2NS2XQAP+NQDHc7TOVRTAMwowKFolW0=
